//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::credentials::Entity as Credentials;
pub use super::email_verified::Entity as EmailVerified;
pub use super::users::Entity as Users;
